
# boost相关
if(BUILD_TARGET_CHIP STREQUAL "ts")
    include_directories("/usr/local/ts_tx5368/thirdparty/boost_1_81/include")
    link_directories("/usr/local/ts_tx5368/thirdparty/boost_1_81/lib/")
    set(Boost_LIBRARIES boost_program_options boost_filesystem)

    install(DIRECTORY /usr/local/ts_tx5368/thirdparty/boost_1_81/ DESTINATION thirdparty)
elseif(BUILD_TARGET_CHIP STREQUAL "bmnn")
    include_directories("/usr/local/bmnn/include/third_party/boost/include")
    link_directories("/usr/local/bmnn/lib/boost_lib/")
    set(Boost_LIBRARIES boost_program_options boost_filesystem)
else()
    if (TARGET_ARCH STREQUAL "x86")
        set(Boost_Dirs "/usr/local/x86-common/boost_1.81_gcc7.5")
    else ()
        set(Boost_Dirs "/usr/local/aarch64-common/boost_1.81_gcc7.5")
    endif()
    find_package(Boost REQUIRED PATHS "${Boost_Dirs}/lib/cmake/" NO_DEFAULT_PATH COMPONENTS filesystem program_options)
    # find_package(Boost 1.45.0 COMPONENTS filesystem regex) 
    if (Boost_FOUND)
        include_directories(${Boost_INCLUDE_DIRS})
        message("!!!!!!!!!!find boost, incude:${Boost_INCLUDE_DIRS}, lib: ${Boost_LIBRARIES}")
    endif()
    include_directories(${Boost_INCLUDE_DIRS})
endif()
# install(DIRECTORY "${Boost_Dirs}" DESTINATION thirdparty)